### ISSUE TITLE
Gunman takes instakill dmage from skeletons

### ISSUE THREAD

**Issue by kohlth** [Zicerite/Gavania-Project#75]
the gunman class seems to take in insta kill damage from mobs

when tested on other classes 
(me level 1 reaper, someone else lvl 36 beast and lvl 16 archangel)
skeletons do a normal amount of damage
 
the current thesis on why is the kevlar vest attribuite (but i could be something else)

**Comment by Zicerite** [comment]
Related to #73

**Comment by Zicerite** [comment]
Patched for Gunman
