### ISSUE TITLE
Gunman Errors

### ISSUE THREAD

**Issue by TheBraver** [Zicerite/Gavania-Project#82]
1. Unable to improve Xync Gunman above 1
2. All attacks drains Gunman's mana when attacking a mob
3. Araw Gunman 2 Mode dealing the same amount of damage as Araw Gunman Mode 1.
4. Mana is buggy for only gunman, Mana reduced to a maximum of 20/20 most of the time. Only seems to effect gunman.

**Comment by Zicerite** [comment]
All patched.
